import { StyleSheet } from '@react-pdf/renderer'

export const pdfColors = {
  accent: '#2D5FD4',
  accentLight: '#EEF3FD',
  text: '#141414',
  textMuted: '#5C5C5C',
  textLight: '#888888',
  border: '#E4E4E4',
  white: '#FFFFFF',
  dark: '#0A0A0A',
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 48,
    fontFamily: 'Helvetica',
    fontSize: 9.5,
    color: pdfColors.text,
    backgroundColor: pdfColors.white,
  },
  coverPage: {
    paddingTop: 64,
    paddingBottom: 48,
    paddingHorizontal: 48,
    backgroundColor: pdfColors.dark,
    color: pdfColors.white,
    fontFamily: 'Helvetica',
  },
  coverLogo: {
    width: 120,
    marginBottom: 48,
  },
  coverLabel: {
    fontSize: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#999999',
    marginBottom: 12,
  },
  coverTitle: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: -0.5,
    lineHeight: 1.15,
    marginBottom: 16,
    maxWidth: 420,
  },
  coverLead: {
    fontSize: 11,
    lineHeight: 1.65,
    color: '#CCCCCC',
    maxWidth: 400,
    marginBottom: 40,
  },
  coverPillars: {
    marginTop: 8,
    gap: 12,
  },
  coverPillar: {
    borderLeftWidth: 2,
    borderLeftColor: pdfColors.accent,
    paddingLeft: 12,
    marginBottom: 12,
  },
  coverPillarTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.white,
    marginBottom: 3,
  },
  coverPillarDesc: {
    fontSize: 9,
    color: '#AAAAAA',
    lineHeight: 1.5,
  },
  coverFooter: {
    position: 'absolute',
    bottom: 40,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#333333',
    paddingTop: 12,
  },
  coverFooterText: {
    fontSize: 8,
    color: '#777777',
  },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
  },
  pageHeaderBrand: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: pdfColors.accent,
  },
  pageHeaderSection: {
    fontSize: 8,
    color: pdfColors.textLight,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: -0.3,
    color: pdfColors.text,
    marginBottom: 6,
  },
  sectionSubtitle: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.55,
    marginBottom: 20,
    maxWidth: 460,
  },
  categoryTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    marginBottom: 14,
    marginTop: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
  },
  serviceBlock: {
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
  },
  serviceName: {
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 4,
  },
  serviceDesc: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.55,
    marginBottom: 6,
  },
  includesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  includeTag: {
    fontSize: 7.5,
    color: pdfColors.textMuted,
    backgroundColor: pdfColors.accentLight,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 2,
  },
  packagesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  packageCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 12,
    marginBottom: 4,
  },
  packageCardHighlight: {
    borderColor: pdfColors.accent,
    backgroundColor: pdfColors.accentLight,
  },
  packageFocus: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: pdfColors.accent,
    marginBottom: 6,
  },
  packageName: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  packageTagline: {
    fontSize: 8.5,
    color: pdfColors.textMuted,
    lineHeight: 1.45,
    marginBottom: 8,
  },
  packageFeature: {
    fontSize: 8,
    color: pdfColors.text,
    lineHeight: 1.5,
    marginBottom: 3,
    paddingLeft: 8,
  },
  packageNote: {
    fontSize: 7.5,
    color: pdfColors.textLight,
    marginTop: 6,
    fontStyle: 'italic',
  },
  packagePrice: {
    fontSize: 8.5,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
    color: pdfColors.text,
  },
  addonsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  addonItem: {
    width: '31%',
    marginBottom: 10,
  },
  addonName: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 3,
  },
  addonDesc: {
    fontSize: 8,
    color: pdfColors.textMuted,
    lineHeight: 1.45,
  },
  processRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  processStep: {
    flex: 1,
    borderTopWidth: 2,
    borderTopColor: pdfColors.accent,
    paddingTop: 8,
  },
  processNum: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    marginBottom: 4,
  },
  processTitle: {
    fontSize: 9.5,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  processDesc: {
    fontSize: 8,
    color: pdfColors.textMuted,
    lineHeight: 1.45,
  },
  ctaBox: {
    marginTop: 24,
    padding: 16,
    backgroundColor: pdfColors.dark,
    borderRadius: 2,
  },
  ctaTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.white,
    marginBottom: 6,
  },
  ctaText: {
    fontSize: 9,
    color: '#BBBBBB',
    lineHeight: 1.55,
    marginBottom: 10,
  },
  ctaContact: {
    fontSize: 8.5,
    color: pdfColors.white,
    lineHeight: 1.6,
  },
  pageFooter: {
    position: 'absolute',
    bottom: 28,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 8,
  },
  pageFooterText: {
    fontSize: 7.5,
    color: pdfColors.textLight,
  },
})
