import { StyleSheet } from '@react-pdf/renderer'

export const pdfColors = {
  accent: '#2D5FD4',
  accentLight: '#EEF3FD',
  text: '#141414',
  textMuted: '#5C5C5C',
  textLight: '#888888',
  border: '#E4E4E4',
  white: '#FFFFFF',
  dark: '#0A0A0A',
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 58,
    paddingHorizontal: 48,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: pdfColors.text,
    backgroundColor: pdfColors.white,
  },

  /* Capa */
  coverPage: {
    paddingTop: 52,
    paddingBottom: 40,
    paddingHorizontal: 48,
    backgroundColor: pdfColors.dark,
    color: pdfColors.white,
    fontFamily: 'Helvetica',
  },
  coverLogo: { width: 110, marginBottom: 40 },
  coverLabel: {
    fontSize: 8,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    color: '#777777',
    marginBottom: 10,
  },
  coverTitle: {
    fontSize: 34,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: -1,
    lineHeight: 1.08,
    marginBottom: 12,
    maxWidth: 400,
  },
  coverTagline: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    marginBottom: 10,
    maxWidth: 380,
  },
  coverLead: {
    fontSize: 10,
    lineHeight: 1.65,
    color: '#BBBBBB',
    maxWidth: 380,
    marginBottom: 28,
  },
  coverDivider: {
    borderTopWidth: 1,
    borderTopColor: '#2A2A2A',
    marginBottom: 20,
  },
  coverPillars: { flexDirection: 'row', gap: 14, marginBottom: 24 },
  coverPillar: {
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    paddingTop: 12,
  },
  coverPillarHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  coverPillarIndex: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    letterSpacing: 1,
  },
  coverPillarTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.white,
    lineHeight: 1.2,
  },
  coverNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  coverNavItem: {
    fontSize: 8,
    color: '#999999',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: 2,
  },
  coverNavItemText: { color: '#CCCCCC', fontSize: 8 },
  coverFooter: {
    position: 'absolute',
    bottom: 32,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#222222',
    paddingTop: 10,
  },
  coverFooterText: { fontSize: 8, color: '#555555' },
  coverFooterLink: { fontSize: 8, color: pdfColors.accent },

  /* Cabeçalho / seção */
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 22,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
  },
  pageHeaderBrand: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: pdfColors.accent,
  },
  pageHeaderSection: { fontSize: 8, color: pdfColors.textLight },
  sectionLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: pdfColors.accent,
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: -0.4,
    color: pdfColors.text,
    marginBottom: 8,
  },
  sectionSubtitle: {
    fontSize: 10,
    color: pdfColors.textMuted,
    lineHeight: 1.6,
    marginBottom: 20,
    maxWidth: 480,
  },
  sectionDivider: {
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    marginVertical: 18,
  },

  /* Apresentação */
  presentationBody: { marginBottom: 22 },
  presentationParagraph: {
    fontSize: 10,
    color: pdfColors.textMuted,
    lineHeight: 1.65,
    marginBottom: 10,
  },
  highlightsRow: { flexDirection: 'row', gap: 10 },
  highlightCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 14,
    borderRadius: 2,
  },
  highlightCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  highlightLabel: {
    fontSize: 7.5,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: pdfColors.textLight,
    marginBottom: 3,
  },
  highlightValue: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
  },

  /* Diferenciais */
  diffGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  diffCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 14,
    marginBottom: 2,
  },
  diffCardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  diffTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 5,
  },
  diffDesc: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  diffResult: {
    fontSize: 8.5,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    lineHeight: 1.4,
  },

  /* Serviços — coluna única premium */
  servicesList: { gap: 0 },
  serviceCard: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
    paddingVertical: 12,
    gap: 12,
  },
  serviceCardBody: { flex: 1 },
  serviceBenefit: {
    fontSize: 8.5,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    marginBottom: 4,
  },
  serviceName: {
    fontSize: 11.5,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 4,
  },
  serviceDesc: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.55,
    marginBottom: 8,
  },
  includesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  includeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    fontSize: 7.5,
    color: pdfColors.textMuted,
    backgroundColor: pdfColors.accentLight,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 2,
  },
  includeTagText: { fontSize: 7.5, color: pdfColors.accent },

  /* Cases */
  casesGrid: { gap: 10 },
  caseCard: {
    flexDirection: 'row',
    gap: 12,
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 14,
    marginBottom: 8,
  },
  caseBody: { flex: 1 },
  caseSegment: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 5,
  },
  caseDelivery: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.5,
    marginBottom: 5,
  },
  caseOutcome: {
    fontSize: 8.5,
    color: pdfColors.accent,
    fontFamily: 'Helvetica-Bold',
    lineHeight: 1.4,
  },

  /* Processo */
  processRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 4,
  },
  processStep: {
    width: '47%',
    borderTopWidth: 2,
    borderTopColor: pdfColors.accent,
    paddingTop: 12,
    marginBottom: 6,
  },
  processHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  processNum: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
    letterSpacing: 0.5,
  },
  processTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 5,
  },
  processDesc: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.5,
  },

  /* Planos */
  packagesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  packageCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 14,
    marginBottom: 4,
  },
  packageCardHighlight: {
    borderColor: pdfColors.accent,
    backgroundColor: pdfColors.accentLight,
  },
  packageBadge: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: pdfColors.white,
    backgroundColor: pdfColors.accent,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginBottom: 8,
    alignSelf: 'flex-start',
    borderRadius: 2,
  },
  packageFocus: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: pdfColors.accent,
    marginBottom: 4,
  },
  packageName: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 5,
  },
  packageTagline: {
    fontSize: 9,
    color: pdfColors.textMuted,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  packageDivider: {
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    marginBottom: 8,
  },
  packageFeatureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 5,
    marginBottom: 4,
  },
  packageFeature: {
    fontSize: 8.5,
    color: pdfColors.text,
    lineHeight: 1.4,
    flex: 1,
  },
  packageFooter: {
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    marginTop: 8,
    paddingTop: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  packageNote: {
    fontSize: 7.5,
    color: pdfColors.textLight,
    flex: 1,
    paddingRight: 6,
    lineHeight: 1.35,
  },
  packagePrice: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.accent,
  },

  /* Avulsos compactos */
  addonsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  addonItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingBottom: 6,
  },
  addonName: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.text,
    marginBottom: 2,
  },
  addonDesc: { fontSize: 8, color: pdfColors.textMuted, lineHeight: 1.4 },

  /* Contato / CTA */
  ctaBox: {
    backgroundColor: pdfColors.dark,
    borderRadius: 2,
    padding: 22,
    marginBottom: 16,
  },
  ctaTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.white,
    marginBottom: 8,
    lineHeight: 1.25,
  },
  ctaText: {
    fontSize: 9.5,
    color: '#AAAAAA',
    lineHeight: 1.6,
    marginBottom: 14,
    maxWidth: 400,
  },
  ctaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: pdfColors.accent,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignSelf: 'flex-start',
    borderRadius: 2,
  },
  ctaButtonText: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.white,
  },
  contactGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  contactItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
  },
  contactLink: { fontSize: 9.5, color: pdfColors.accent },
  contactText: { fontSize: 9.5, color: pdfColors.text },

  /* Links */
  link: { color: pdfColors.accent, textDecoration: 'none' },
  linkMuted: { color: '#CCCCCC', textDecoration: 'none' },

  /* Rodapé */
  pageFooter: {
    position: 'absolute',
    bottom: 22,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 7,
  },
  pageFooterText: { fontSize: 7.5, color: pdfColors.textLight },
})
